export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_INPUT_PASSWORD_CHANGED = 'USER_INPUT_PASSWORD_CHANGED';

export const USER_TRY_TO_LOG_IN = 'USER_TRY_TO_LOG_IN';
export const USER_TRY_TO_LOG_OUT = 'USER_TRY_TO_LOG_OUT';

export const USER_TRY_DELETE_ACCOUNT = 'USER_TRY_DELETE_ACCOUNT';
export const USER_DELETED_ACCOUNT = 'USER_TRY_DELETED_ACCOUNT';
export const USER_GET_ERROR_DELETE = 'USER_GET_ERROR_DELETE';
export const USER_GET_ERROR_TOKEN_DELETE = 'USER_GET_ERROR_TOKEN_DELETE';

export const USER_WANT_UPDATE_DATA = 'USER_WANT_UPDATE_DATA';

export const GET_USER_UPDATING_DATA = 'GET_USER_UPDATING_DATA';
export const GET_USER_UPDATED_DATA = 'GET_USER_UPDATED_DATA';
export const GET_USER_UPDATE_DATA_FAIL = 'GET_USER_UPDATE_DATA_FAIL';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_USER_LOGIN_LOADING = 'GET_USER_LOGIN_LOADING';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const USER_INPUT_NAME_CHANGED = 'USER_INPUT_NAME_CHANGED';
export const USER_INPUT_SURNAME_CHANGED = 'USER_INPUT_SURNAME_CHANGED';
export const USER_INPUT_BIRTHDAY_CHANGED = 'USER_INPUT_BIRTHDAY_CHANGED';

export const USER_WANT_REGISTRATION = 'USER_WANT_REGISTRATION';

export const GET_USER_REGISTRATION_LOADING ='GET_USER_REGISTRATION_LOADING';
export const GET_USER_REGISTERED = 'GET_USER_REGISTERED';
export const GET_USER_REGISTRATION_FAIL = 'GET_USER_REGISTRATION_FAIL';

export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const GET_POST_DELETING = 'GET_POST_DELETING';
export const GET_POST_DELETED = 'GET_POST_DELETED';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const FORM_POST_LOADING = 'FORM_POST_LOADING';
export const FORM_POST_LOADING_DISABLE = 'FORM_POST_LOADING_DISABLE';

export const FORM_POST_DISABLED_STATE = 'FORM_POST_DISABLED_STATE';

export const INPUT_TITLE_BY_POST_CHANGED = 'INPUT_TITLE_BY_POST_CHANGED';
export const INPUT_POST_CHANGED = 'INPUT_POST_CHANGED';

export const GET_POST_PUBLIC_LOADING = 'GET_POST_LOADING';
export const GET_POST_PUBLIC = 'GET_POST_PUBLIC';
export const GET_POST_PUBLICATION_FAIL = 'GET_POST_PUBLICATION_FAIL';

export const GET_POST_UPDATING = 'GET_POST_UPDATING';
export const GET_POST_UPDATED = 'GET_POST_UPDATED';
export const GET_POST_UPDATE_FAIL = 'GET_POST_UPDATE_FAIL';

export const GET_POST_SELECT_LOADING = 'GET_POST_SELECT_LOADING';
export const GET_POST_SELECT_LOADED_SUCCESS = 'GET_POST_SELECT_LOADED_SUCCESS';
export const GET_POST_SELECT_LOADED_FAIL = 'GET_POST_SELECT_LOADED_FAIL';

export const USER_WANT_UPDATE_POST = 'USER_WANT_UPDATE_POST';

export const USER_INPUT_COMMENT_CHANGED = 'USER_INPUT_COMMENT_CHANGED';

export const USER_TRY_COMMENTING = 'USER_TRY_COMMENTING';
export const USER_TRY_TO_COMMENT_IN = 'USER_TRY_TO_LOG_IN';
export const COMMENT_PUBLIC_FAIL = 'COMMENT_PUBLIC_FAIL';

export const GET_COMMENT_PUBLIC_LOADING = 'GET_COMMENT_LOADING';
export const GET_COMMENT_PUBLIC = 'GET_COMMENT_PUBLIC';
export const GET_COMMENT_PUBLICATION_FAIL = 'GET_COMMENT_PUBLICATION_FAIL';

export const FORM_COMMENT_LOADING_DISABLE = 'FORM_COMMENT_LOADING_DISABLE';

export const GET_COMMENT_DELETING = 'GET_COMMENT_DELETING';
export const GET_COMMENT_DELETED = 'GET_COMMENT_DELETED';
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL';

export const OPEN_FORM_COMMENT = 'OPEN_FORM_COMMENT';

export const GET_COMMENTS_SELECT_LOADING = 'GET_COMMENTS_SELECT_LOADING';
export const GET_COMMENTS_SELECT_LOADED = 'GET_COMMENTS_SELECT_LOADED';
export const GET_COMMENTS_SELECT_FAIL = 'GET_COMMENTS_SELECT_FAIL';

export const DISABLE_COMMENT_DOWN_POST = 'DISABLE_COMMENT_DOWN_POST';

export const LIKE_POST_LOADING = 'LIKE_POST_LOADING';
export const LIKE_POST_LOADED_SUCCESS = 'LIKE_POST_LOADED_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

